### ISSUE TITLE
혹시 유사도 비교 분석 부분이 어디있는지 알 수 있나요?

### ISSUE THREAD

**Issue by cocoflekd** [olrlobt/OX-POSE#10]
아무리 찾아도 안나와요

**Comment by olrlobt** [comment]
안녕하세요. 오래전에 한 프로젝트라 기억이 잘 안 나지만, 조금 답변 드리자면

좌표의 유사도를 구하는 부분은 [코사인 유사도](https://github.com/olrlobt/OX-POSE/blob/master/src/main/java/com/combo/oxpose/mediapose/PoseService.java#L278)로 유사도를 구하는 방법을 사용하였고, 

`OX-POSE/src/main/java/com/combo/oxpose/mediapose/PoseService.java`



```java
 /**
     * 코사인 유사도를 계산하는 함수
     *
     * @return 벡터 A와 벡터 B의 유사도
     */
    public double cosineSimilarity(PoseKeyPoint poseWorldLandmarks1, PoseKeyPoint poseWorldLandmarks2) {
        double[] A = {poseWorldLandmarks1.getX(), poseWorldLandmarks1.getY()
                , poseWorldLandmarks1.getZ()};
        double[] B = {poseWorldLandmarks2.getX(), poseWorldLandmarks2.getY()
                , poseWorldLandmarks2.getZ()};

        return (dotProduct(A, B)) / ((Math.sqrt(dotProduct(A, A))) * (Math.sqrt(dotProduct(B, B))));
    }
```

이렇게 구한 유사도를 기반으로 일정 수치 이상 값이 벗어나면,
3D상의 좌표를 산수 연산하여 다른 영상에 위에서 보정할 좌표로 찍어주게끔 구현하였었습니다.

실제 분석 부분에서는 보정할 좌표를 찍어서 나타내주는 것 외에는 할 수 있을만한게 없었구요,
그래서 프로젝트를 완벽하게 마무리는 못한 체, 다른 일을 하고 있습니다 😅
